default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: todoapp
  host: postgres
  port: 5432

development:
  <<: *default
  database: todoapp_dev

test:
  <<: *default
  database: todoapp_test

production:
  url: <%= ENV['DATABASE_URL'] %>
